#include "../SimpleKit.WindowsRuntime.Shared/MidlUtils.h"

namespace SimpleKit.WindowsRuntime.UI.Controls
{
	[default_interface]
	[webhosthidden]
	[contentproperty("Title")]
	unsealed runtimeclass TitleBar : Windows.UI.Xaml.Controls.Control
	{
		TitleBar();
		void SetTitleBarForCurrentView();

		DEPENDENCY_PROPERTY(Title, Object);
		DEPENDENCY_PROPERTY(Icon, Windows.UI.Xaml.Controls.IconElement);
	}
}