namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	[webhosthidden]
	runtimeclass NavigationHelper
	{
		NavigationHelper(Windows.UI.Xaml.Controls.Page page);
		NavigationHelper(Windows.UI.Xaml.Controls.Page page, Boolean useNavigationShortcuts);

		String PageKey{ get; };

		Boolean CanGoBack();
		void GoBack();

		Boolean CanGoForward();
		void GoForward();

		Windows.Foundation.Collections.IMap<String, Object> LoadState(Windows.UI.Xaml.Navigation.NavigationMode navigationMode);
		void SaveState(Windows.Foundation.Collections.IMap<String, Object> state);
	}
}
