import "LoadStateEventArgs.idl";

namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	[bindable]
	[webhosthidden]
	unsealed runtimeclass NavigationHelper : Windows.UI.Xaml.DependencyObject
	{
		NavigationHelper(Windows.UI.Xaml.Controls.Page page);

		Boolean CanGoBack();
		void GoBack();

		Boolean CanGoForward();
		void GoForward();

		void HandleNavigationToPage(Windows.UI.Xaml.Navigation.NavigationEventArgs args);
		void HandleNavigatedFromPage(Windows.UI.Xaml.Navigation.NavigationEventArgs args);

		void SaveState(Windows.Foundation.Collections.IMap<String, Object> state);

		event Windows.Foundation.EventHandler<SimpleKit.WindowsRuntime.UI.Navigation.LoadStateEventArgs> StateRestorationStarted;
		event Windows.Foundation.EventHandler<Windows.UI.Xaml.Navigation.NavigationEventArgs> PageStateRequested;
	}
}
