import "NavigationHelper.idl";

namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	[webhosthidden]
	unsealed runtimeclass NavPage : Windows.UI.Xaml.Controls.Page
	{
		NavPage();
		NavPage(Boolean useNavigationShortcuts);

		Boolean TryLoadState(Windows.UI.Xaml.Navigation.NavigationMode navigationMode);
		void SaveState();

		SimpleKit.WindowsRuntime.UI.Navigation.NavigationHelper PageHelper{ get; };
		Windows.Foundation.Collections.IMap<String, Object> PageState{ get; };
	};
}
