import "NavigationHelper.idl";

namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	[webhosthidden]
	unsealed runtimeclass NavPage : Windows.UI.Xaml.Controls.Page
	{
		NavPage();
		NavPage(Boolean useNavigationShortcuts);

		SimpleKit.WindowsRuntime.UI.Navigation.NavigationHelper PageHelper{ get; };
	};
}
