#include "../SimpleKit.WindowsRuntime.Shared/MidlUtils.h"

namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	[webhosthidden]
	runtimeclass SessionStateManager : Windows.UI.Xaml.DependencyObject
	{
		SessionStateManager();
		static void Initialize();

		static Windows.Foundation.Collections.IMap<String, Object> SessionState { get; };

		static Windows.Foundation.IAsyncAction SaveAsync();
		static Windows.Foundation.IAsyncAction RestoreAsync();
		static Windows.Foundation.IAsyncAction RestoreAsync(String sessionBaseKey);

		ATTACHED_PROPERTY(SessionKey, String, Windows.UI.Xaml.Controls.Frame);

		static void RegisterFrame(Windows.UI.Xaml.Controls.Frame frame, String sessionStateKey);
		static void RegisterFrame(Windows.UI.Xaml.Controls.Frame frame, String sessionStateKey, String sessionBaseKey);

		static void UnregisterFrame(Windows.UI.Xaml.Controls.Frame frame);

		static Windows.Foundation.Collections.IMap<String, Object> SessionStateForFrame(Windows.UI.Xaml.Controls.Frame frame);
	}
}
