namespace SimpleKit.WindowsRuntime.UI.Navigation
{
	[default_interface]
	runtimeclass StateRequestedEventArgs
	{
		StateRequestedEventArgs(Windows.Foundation.Collections.IMap<String, Object> pageState);

		Windows.Foundation.Collections.IMap<String, Object> PageState{ get; };
	}
}
