namespace SimpleKit.WindowsRuntime.UI.Controls
{
	[default_interface]
	[webhosthidden]
	runtimeclass ExtendedTitleBar : Windows.UI.Xaml.Controls.UserControl
	{
		ExtendedTitleBar();

		Object Title;
		static Windows.UI.Xaml.DependencyProperty TitleProperty{ get; };

		Object Icon;
		static Windows.UI.Xaml.DependencyProperty IconProperty{ get; };
	}
}
