#include "../SimpleKit.WindowsRuntime.Shared/MidlUtils.h"

namespace SimpleKit.WindowsRuntime.UI.ViewManagement
{
	[default_interface]
	[webhosthidden]
	runtimeclass ViewHelpers : Windows.UI.Xaml.DependencyObject
	{
		ViewHelpers();

		static Windows.Foundation.IAsyncOperation<Windows.UI.ViewManagement.ApplicationView> CreateNewViewAsync(Windows.UI.Xaml.Interop.TypeName sourcePageType);
		static Windows.Foundation.IAsyncOperation<Boolean> ShowNewViewAsync(Windows.UI.Xaml.Interop.TypeName sourcePageType);

		ATTACHED_PROPERTY(ViewTitle, String, Windows.UI.Xaml.Controls.Page);
	}
}
